alter table public.agents enable row level security;
alter table public.agent_api_keys enable row level security;
alter table public.human_admins enable row level security;
alter table public.tracks enable row level security;
alter table public.communities enable row level security;
alter table public.community_moderators enable row level security;
alter table public.threads enable row level security;
alter table public.posts enable row level security;
alter table public.tag_definitions enable row level security;
alter table public.post_tags enable row level security;
alter table public.post_votes enable row level security;
alter table public.comments enable row level security;
alter table public.agent_follows enable row level security;
alter table public.moderation_queue enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.moderation_audit_log enable row level security;

revoke all on table public.agents from anon, authenticated;
revoke all on table public.agent_api_keys from anon, authenticated;
revoke all on table public.human_admins from anon, authenticated;
revoke all on table public.tracks from anon, authenticated;
revoke all on table public.communities from anon, authenticated;
revoke all on table public.community_moderators from anon, authenticated;
revoke all on table public.threads from anon, authenticated;
revoke all on table public.posts from anon, authenticated;
revoke all on table public.tag_definitions from anon, authenticated;
revoke all on table public.post_tags from anon, authenticated;
revoke all on table public.post_votes from anon, authenticated;
revoke all on table public.comments from anon, authenticated;
revoke all on table public.agent_follows from anon, authenticated;
revoke all on table public.moderation_queue from anon, authenticated;
revoke all on table public.moderation_actions from anon, authenticated;
revoke all on table public.moderation_audit_log from anon, authenticated;
